### ISSUE TITLE
Videojs player.src doesn't work

### ISSUE THREAD

**Issue by jhemmmm** [cdnbye/mp4-p2p-engine#1]
Hello,

I have tried using this thing and it won't work if you added the video on player.src. It only works if you added it directly from <source

**Comment by snowinszu** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Videojs-contrib-mp4</title>
    <link href="http://vjs.zencdn.net/5.19.2/video-js.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/5.19.2/video.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/cdnbye-mp4@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/cdnbye-mp4@latest/dist/videojs-contrib-mp4.min.js"></script>
</head>
<body>
<video id="player" class="video-js vjs-default-skin" height="360" width="640" controls preload="none">
</video>
<script>
    var player = videojs('#player', {
        sources:[
            {
                src: 'https://webtorrent.io/torrents/Sintel/Sintel.mp4',
            }
        ],
        html5: {
            mp4Config: {
                p2pConfig: {
                    // logLevel: 'debug',
                    // Other p2pConfig options provided by CDNBye
                }
            }
        }
    });
</script>
</body>
</html>

**Comment by snowinszu** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Videojs-contrib-mp4</title>
    <link href="http://vjs.zencdn.net/5.19.2/video-js.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/5.19.2/video.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/cdnbye-mp4@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/cdnbye-mp4@latest/dist/videojs-contrib-mp4.min.js"></script>
</head>
<body>
<video id="player" class="video-js vjs-default-skin" height="360" width="640" controls preload="none">
    
            
</video>
<script>
    var url = 'https://webtorrent.io/torrents/Sintel/Sintel.mp4'
    var player = videojs('#player', {
        sources:[
            {
                src: url
            }
        ],
        html5: {
            mp4Config: {
                p2pConfig: {
                    logLevel: 'debug',
                    // Other p2pConfig options provided by CDNBye
                }
            }
        }
    });

    setTimeout(function () {

        // player.dispose();
        player.src(url);
        player.load(url);

    }, 10000)

</script>
</body>
</html>

**Comment by jhemmmm** [comment]
Oh my bad. Everything seems to be working fine, I have just tried the video url:
`https://webtorrent.io/torrents/Sintel/Sintel.mp4`

And it works perfectly fine. I am not sure why it is not working on my videos. Anyway. thanks.

Another question. What do you mean by  "only supports MP4,

>  smaller size,"

**Comment by snowinszu** [comment]
Because webtorrent supports many file format, such as pdf mp4 mp3, leading larger sdk size
